### ISSUE TITLE
Strip markdown heading syntax from #flashcard titles  

### ISSUE THREAD

**Issue by orionrush** [NeuraCache/flashcards#1]
I've been using Obsidian, but other editors would apply as well. 

## Scenario: 
You have a lot of flashcards in a single markdown file, ie 20+ on a topic. It becomes increasingly difficult to see the body of each card in order to continue to make edits, as there is no visual separation between them. 

One solution would be to add a markdown heading to the flashcard title/question, but this creates other issues once imported into NeuraCache as this issue demonstrates.  

Consider the following card:
```
## What is function hoisting in JavaScript? #flashcard #js_functions
// Question text
---
```
Once a file is imported into NeuraCache, any cards that use a preceding `#` will:
- Single `# `: tags on the question line are imported empty, ie no flashcards at all under `#js_functions`
- Multiple  `## `, `### `, `####` etc are interpreted as categories of their own and thus skew the stats on the home screen. 

## Ideal solution: (full support)
For markdown files, within the question line, NeuraCache should filter out valid [markdown headings](https://www.markdownguide.org/basic-syntax/#headings) such as `# `,  `## `, `### `, `####`

## Alternate syntax solution: (update documentation)
Alternatively, document the preferred use of Markdown's [alternative heading syntax](https://www.markdownguide.org/basic-syntax/#alternate-syntax), which uses a multi-character `=` on a new line underneath the heading, like so:
```
What is function hoisting in JavaScript? #flashcard #js_functions
====
// Question text
---
```

While with alternate the `====` will make it into the question body, it does not have any of the other side effects listed here, however, it does introduce some other potential issues. 

Personally prefixing a question with multiple `#` is the ideal behaviour as its familiar to most users, easy to do, and easy to use 'find and replace' to modify. In my experience, many Markdown editors do not behave well with multi-line search and replace, like you may need to with the alternative heading syntax. 

The `#` syntax allows for headings (h1-6), where technically the alternative syntax allows for h1 and h2 using multi-character `===` or  `---` which of course may confuse the NeuraCache importer.

**Comment by NeuraCache** [comment]
NeuraCache iOS 2.20 and Android 2.13.3 filters out # ## ### tags 👍
