### ISSUE TITLE
iOS iCloud Markup sync does not work

### ISSUE THREAD

**Issue by ksandvik** [NeuraCache/flashcards#13]
If you select a folder from iCloud to get all the Neuracache tags, in most cases you get nothing out and a message such as : "Some of your .md files  are not yet sync:ed via iCloud".

I verified that the content shows via the Files app. Interestingly after verification the contents of that specific .md file are parsed in. So I suspect there are issues in the code where the iCloud based .md file has to be opened so a download happens from the cloud and this way the parsing works. Or then the parsing of content that is only in the cloud is not working properly.

Neuralink 2.14, iOS 14.2

**Comment by AndroidGecko** [comment]
Hey 

That is a known issue. 👍

iOS does not sync your files unless you explicitly navigate to them in an app like "Files".

> "Some of your .md files are not yet synced via iCloud".

NeuraCache shows this dialog when it encounters a file with a ".icloud" extension.
It means that the file reference is there, but the contents are not yet synced by iOS.
Once you open the folder in "Files" — iOS downloads the contents, and NeuraCache can function normally.

We noticed that if you place your files on your desktop — it does sync them more often.
Unfortunately, there is not much we can do as there is no "force sync" option.

We are working on better ways like Google Drive or Dropbox.
Some of our users also use syncthing (https://syncthing.net/)

Best

**Comment by ksandvik** [comment]
Hmm, interesting that this could work with other iOS apps, maybe related to the sync protocol and making files to download. Meanwhile, I just need to hack a script that finds all the .md files and concatenates them into a single .md file that I load in via Files and then they could be parsed. But I doubt many end users know how to do something like this.

**Comment by NeuraCache** [comment]
Also, please see our updated docs which include "Syncing your cards" section 👍
https://wiki.neuracache.com/markdown-flashcards
