### ISSUE TITLE
Using batch flashcard list format with a single item doesn't work

### ISSUE THREAD

**Issue by transportstudio** [NeuraCache/flashcards#14]
The batch format for Question/Answer Flashcards and Spaced Repetition is great, very convenient! But it is not intuitive for it to break if the list has only one item in it.

This imports properly into NeuraCache:

```
#flashcard #optionaltag1 #optionaltag2 
- question 1 : answer 1
- question 2 : answer 2
```

This does not import properly into NeuraCache (instead the flashcard content goes all the way to end of file or --- ):

```
#flashcard #optionaltag1 #optionaltag2 
- question 1 : answer 1
```

The same applies for using spaced instead of flashcard.

This works:

```
#spaced #optionaltag1 #optionaltag2 
- content 1
- content 2
```

This does not work:

```
#spaced #optionaltag1 #optionaltag2 
- content 1
```

Often I will have a note where I want to create one flashcard/spaced to begin with, while intending to add more in the future. It's awkward to need to change from a single card format to the batch format. 

Could you please support the batch format with a list with just one item? Thanks

**Comment by NeuraCache** [comment]
Hey 👋
The batch format never made it to the NeuraCache as it was defined in the spec.

Instead, we've added, simpler Tag Groups, you can read more here:
https://wiki.neuracache.com/cb59590a6b98480a926a798016cef590

please also see updated markdown docs with many examples:
https://wiki.neuracache.com/markdown-flashcards
