### ISSUE TITLE
Android: automate or schedule folder import of Markdown files (i.e. sync)

### ISSUE THREAD

**Issue by transportstudio** [NeuraCache/flashcards#15]
It's great that NeuraCache can integrate with so many different sources of cards and I understand it must be a lot of work to support them. But there is something frustrating me about Markdown folder import.

**Currently**, importing a folder of Markdown notes is done by manually selecting that in the app, and then it needs to scan for several minutes (for my collection of 3,000 notes, synced with PC using Syncthing). If I then edit a Markdown note, this change doesn't get into NeuraCache until after I manually import the folder again.

**Ideally**, NeuraCache would be able to _remember_ that folder and _watch_ it (or even multiple different folders and multiple different integrations - Evernote, Roam, etc). Hopefully without using too much battery. Alternatively, being able to schedule a folder scan to occur at a specified time interval would be better than nothing. (For someone with just a few notes, this could be hourly or something - in my case I would probably only do it daily if it takes several minutes).

I hope that's possible - I guess you have probably thought about it but I didn't see it listed as an issue here or on reddit, so thought it was worth asking. Also I'm not entirely sure whether this is the right place to raise issues about the Android app or if it is just for the Markdown syntax. Thanks

**Comment by NeuraCache** [comment]
Added in Android 2.13 as "Select Folder to Observe".
Sync happens in the background every ~6hours or if you pull down on the card list.

Additionally to this, NeuraCache iOS 2.20 introduces a "Single source of truth" 
https://twitter.com/neuracache/status/1517210509501771781
This will come in the next update for Android.
