### ISSUE TITLE
Easily remove flashcards not present in synced files

### ISSUE THREAD

**Issue by orionrush** [NeuraCache/flashcards#3]
Presently, if #flashcard titles are changed or removed from the sync source, they remain in NeuraCache, potentially polluting the pool of flashcards with outdated incorrect cards. 

For example, when generating a large set of cards, an imported file may contain several changes to titles, cards removed and new cards.

It would be nice to use your sync folder as the single 'source of truth', and with the requisite warnings to user, be able to remove cards no present in the sync file.

**Comment by NeuraCache** [comment]
👍 
I was thinking about this for markdown.
Current Roam sync (via files) has a switch "Delete missing cards" which makes it work as a "source of truth".
I will add something similar to markdown.

Thanks

**Comment by NeuraCache** [comment]
resolved in iOS 2.20 (coming soon to Android)
https://twitter.com/neuracache/status/1517210509501771781
