### ISSUE TITLE
iOS: simlify notes syncing UI 

### ISSUE THREAD

**Issue by orionrush** [NeuraCache/flashcards#6]
When syncing Markdown files, which is mainly how I use NeuraCache I have to scroll past a host of services that I don't use to get to the 'sync' button. Im finding as Im bringing on a new category of flashcards I spend a bit of time, syncing and resyncing them. 

<img width="375" alt="Screenshot 2020-12-04 at 11 52 32 am" src="https://user-images.githubusercontent.com/788150/101160624-41c53600-3627-11eb-8e8a-d30cfb7e7745.png">

It would be nice if in the app setting you could enable or disable the services you actually use shorten that list a bit. 

Also, if the settings for these sources were moved to a more central 'services'(?) section of the app's preferences, then options like "select folder to observe" could also be moved there, further simplifying this UI. 

Perhaps there are more intuitive places to add sync functionality? 
Where might people contextually want to sync their notes? 

For example maybe under the (...) menu in the category notes list,  there could be a 'sync category' option, whereby the sources for that category or file type would be synced? Maybe this spot isn't ideal, but these are interesting questions to ask. 

<img width="375" alt="Screenshot 2020-12-04 at 11 53 55 am" src="https://user-images.githubusercontent.com/788150/101161044-e182c400-3627-11eb-8ec6-5720b306dcd4.png">

Again this is another issue that relates more to the app UI rather than the Markdown functionality, however, it _does_ have to do with how _I_ interact with Markdown in the UI :). If you create a repo for the iOS app to collect issues,  then I'd happily move these observations there.

**Comment by NeuraCache** [comment]
Thanks @orionrush 

These are great observations.
I was thinking about two ideas for this issue:

1. pull-down list of notes to run sync on all connected sources.
2. A sync button on the right bottom of the notes list (similar to study) to run sync on all connected sources.

This repo is fine for these types of issues 👍 (markdown related)

Will be deciding what is the best way to solve this.

**Comment by golflabel** [comment]
> Thanks @orionrush
> 
> These are great observations.
> I was thinking about two ideas for this issue:
> 
> 1. pull-down list of notes to run sync on all connected sources.
> 2. A sync button on the right bottom of the notes list (similar to study) to run sync on all connected sources.
> 
> This repo is fine for these types of issues 👍 (markdown related)
> 
> Will be deciding what is the best way to solve this.

I would **love** to see this feature!

**Comment by NeuraCache** [comment]
This has been resolved using pull down to refresh on iOS 👍
