### ISSUE TITLE
iCloud Sync problems

### ISSUE THREAD

**Issue by mkschulze** [NeuraCache/flashcards#9]
Hello, it looks like I cannot get iCloud to sync properly.

Is there any way how to make them be friends or another service? Dropbox also still doesn't work yet, right?

[![Bild img_3477j8j4x.png auf abload.de](https://abload.de/img/img_3477j8j4x.png)](https://abload.de/image.php?img=img_3477j8j4x.png)

But in finder it actually shows as synced:

![Bildschirmfoto 2021-02-21 um 12 18 03](https://user-images.githubusercontent.com/3390820/108624696-c5ccd400-7446-11eb-8eb3-4a6dca0dc9e7.png)

**Comment by AndroidGecko** [comment]
Thanks!

Could you check on your iPhone "Files" app if they've made it to the phone?
NeuraCache shows this dialog when it finds ".md.icloud" files in a folder (instead of ".md")

If that does not work, try using "import markdown file" from that folder — and see if that works.

Best

**Comment by mkschulze** [comment]
Ah ok, that worked yes. In files I had to download them from iCloud it seems. Hm, is there a way to tell iCloud to always download the files in that folder?

**Comment by mkschulze** [comment]
Couldn't find an option but I set that folder to be a favourite in the files app now, maybe it gets watched then. Need to test further.
